doc: add mention of Managed Kafka
nodeshift-starters/reactive-example pull request #30
Opened 2021-06-21 20:58 UTC by mhdawson

Add mention of Managed Kafka as an option versus
installing a Kafka instance into the cluster.

Signed-off-by: Michael Dawson <mdawson@devrus.com>

2021-06-21 20:59 UTC, mhdawson commented on README.md
> +kube-service-bindings](https://github.com/nodeshift/kube-service-bindings)
```suggestion
[kube-service-bindings](https://github.com/nodeshift/kube-service-bindings)
```

2021-06-21 21:10 UTC, helio-frota requested changes

2021-06-21 21:10 UTC, helio-frota commented on README.md
> +on the OpenShift topoloy page onto icon for the Kafka instance.
nit typo topology, other than that LGTM.

2021-06-22 19:24 UTC, mhdawson commented on README.md
> +on the OpenShift topoloy page onto icon for the Kafka instance.
```suggestion
on the OpenShift topology page onto icon for the Kafka instance.
```

2021-06-22 19:25 UTC, mhdawson commented
@helio-frota fixed.

2021-06-22 19:52 UTC, helio-frota approved these changes

2021-06-22 19:53 UTC, merged